#!/usr/bin/env bash

set -e
cd "$(dirname "$0")/.."

set +e

exit_code=0

ruff format . || exit_code=1
ruff check . --fix || exit_code=1
mypy custom_components/basestation || exit_code=1

exit $exit_code